### ISSUE TITLE
[Grammar error]:  'tameble' dragons

### ISSUE THREAD

**Issue by LimemonadeShark** [HowToOwnADragon/Website#5]
### Grammar error report rule check (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/HowToOwnADragon/Website/issues' target='_blank'>has not already been reported</a>

### Where can we find the Grammar error?

https://howtoownadragon.com/Wiki/Dragons/Boulder/Gronckle

### Elaborate.

In the Interactions section, it says "tameble" instead of "tameable"
(this is also in the terrible terror, deadly nadder and MN tabs)

**Comment by Justindraak1** [comment]
I see, Welp that means its in every page so imma fix that now

**Comment by Justindraak1** [comment]
Fixed, thank you for reporting! (though this would be more a spelling mistake than a grammar error imo
