### ISSUE TITLE
Tracker Boulder class

### ISSUE THREAD

**Issue by LimemonadeShark** [HowToOwnADragon/Website#6]
### Spelling mistake report rule check (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/HowToOwnADragon/Website/issues' target='_blank'>has not already been reported</a>

### Where can we find the Spelling mistake?

https://howtoownadragon.com/Wiki/Dragons/Tracker_Class#

### Elaborate.

In the Tracker class tab, it says "...list of all the dragons that belong in the **Boulder** Class..."

**Comment by Justindraak1** [comment]
oh god
please tell me it doesn't say that for every class

**Comment by Justindraak1** [comment]
just checked, its just the tracker class, ty for reporting, will be fixed before the next testrun
