### ISSUE TITLE
Spawn Biomes list: Stormfly

### ISSUE THREAD

**Issue by LimemonadeShark** [HowToOwnADragon/Website#8]
### Incorrect data report rule check (please read carefully)

- [X] I have checked that this incorrect data <a href='https://github.com/HowToOwnADragon/Website/issues' target='_blank'>has not already been reported</a>

### Where can we find the incorrect data?

https://howtoownadragon.com/Wiki/Dragons/Tracker/Deadly_Nadder

### Elaborate.

In the "Spawn Biomes" section with the variants, there's a tab for Stormfly with biomes being listed despite Stormfly not spawning naturally.
 (For example, in the Gronckle page, Meatlug doesn't have a 'biome spawn' list)

### Version

Alpha 0.0.6 or older

**Comment by Justindraak1** [comment]
Fixed
